CREATE VIEW ZQEXP_T100CREDITORDER_SYG_C AS
SELECT t.NUMORD,
       t.CODUSR,
       t.CODEUSR,
       t.CODTYPORD,
       t.CODSTATUS,
       t.CODDIV,
       t.CODBLCCAUSE,
       t.DTEORD,
       t.DTEDELIV,
       t.CODTYPDELIV,
       t.DTEEVA,
       t.CODPAYTRM,
       t.CODPAYMOD,
       GET_CUSTOMER_CODE(t.CODDIV,t.CODCUSTINV),
       t.CODVATMGMT,
       t.CODCUSTINV,
       t.CODLIST,
       t.CODCUR,
       t.numord || t.codusr as NUMORDREF,
       t.NUMORDHOST,
       t.NUMORDCUST,
       t.DTEORDCUST,
       t.CODASSORTMENT,
       t.CODCANVASS,
       t.CODMODSHIP,
       t.CODMODDELIV,
       t.CODAGREEMENT,
       t.OBJID,
       t.DESAGREEMENT,
       t.CODUSRAUT,
       t.CODAGREECLASS,
       t.DTEAUT,
       t.CODTYPAUT,
       t.DESAUT,
       t.DTETOSERVER,
       t.DTETOHOST,
       t.GROSSAMOUNT,
       t.NETAMOUNT,
       t.TAXAMOUNT,
       t.VATAMOUNT,
       t.INCREASEAMOUNT,
       t.DISCOUNTAMOUNT,
       t.GIFTAMOUNT,
       t.DTECRE,
       t.DTEMOD,
       t.DTELCK,
       t.CODUSRLCK,
       t.CODUSRMOD,
       t.FLGANN,
       t.PGMMODCL,
       t.PGMMODDB,
       t.CODABI,
       t.CODCAB,
       t.DESBAN,
       t.DESBRA,
       t.DESADDR,
       t.DESLOC,
       t.DESPRV,
       t.QTYTOT,
       t.CODPRV,
       t.UMQTYTOT,
       t.CODACCOUNT,
       t.FLGRETURN,
       t.FLGHOSTED,
       t.FLGCONFIRMED,
       t.IDSESSIONLCK,
       t.CODWHS,
       t.CODSHIPPER,
       t.CODAZCAPP,
       CODAZCBEN,
       t.DTEPRICE,
       t.CODTYPSALE,
       t.FLGCHECKPROMO,
       t.CODAGREETYPE,
       t.CODSTATUSMAN,
       t.DISCOUNTAMOUNTOUTINV,
       t.CODTYPORDCUST,
       t.CODUSR3,
       t.DTEDELIVTO,
       t.CODCIN,
       t.FLGUMORD2,
       t.NETAMOUNTTEO,
       t.NETAMOUNTMIN,
       t.NETAMOUNTMAX,
       t.CODUSR4,
       t.CODUSR2,
       t.CODBUYEREDI,
       '' AS CODCUSTINVEDI,
       t.CODCUSTDELIVEDI,
       t.CODSELLEREDI,
       t.CODUSR6,
       t.CODPDV,
       t.CODCUSTCONC,
       t.CODIBAN,
       t.CODUSRCRE,
       t.BACKAMOUNT,
       t.TOTPALLETS,
       t.GROSSWEIGHT,
       t.TOTMC,
       t.DTEPROPDELIV,
       t.DOCUMENTKEY,
       t.CODUSR5,
       t.CODUSRMODREAL,
       t.CODUSRCREREAL,
       t.IDSURVEY,
       t.CODCUSTSALE,
       t.FLGPROCESSEDEDI,
       t.FLGEDI,
       t.NUMESENZIONE,
       t.DTEDELIV2,
       t.DTEDELIV3,
       t.DTEDELIV4,
       t.DTEDELIV5,
       t.IDROUTE,
       t.NUMDOC,
       t.DTECLOSE,
       t.RETURNAMOUNT,
       t.GPSVALLATITUDE,
       t.GPSVALLONGITUDE

  FROM T100ORDHEAD t
 WHERE NVL(t.DTETOHOST, to_Date('30121899', 'ddmmyyyy')) =
       to_Date('30121899', 'ddmmyyyy')
   AND (t.CODUSR, t.CODDIV, TRUNC(t.DTEORD)) IN
       (SELECT CODUSR, CODDIV, TRUNC(DTEDAY) FROM TA0300SELLINGDAY WHERE Z_FLGSETTLED = -1 ) --SEND ONLY AFTER SETTLEMENT
   AND (t.DTELCK IS NULL OR t.DTELCK < SYSDATE - 1)
   AND t.CODSTATUS IN ('11', '6') --INVOICED INVOICE AND DELIVERED DELIVERY ORDERS
   AND t.CODDIV = 'SYG'
   AND TRIM(t.CODTYPORD) IN ('70', '80')
   AND TRIM(t.CODPAYMOD) = 'CR'
;
